/MuSIC_Detector/dipField /Users/scook/code/MuSIC/simulation/MuSIC_5_detector_sim/MuSIC5/MuSIC5_detector/fieldmap/fieldmap_dipole.txt
/MuSIC_Detector/solField /Users/scook/code/MuSIC/simulation/MuSIC_5_detector_sim/MuSIC5/MuSIC5_detector/fieldmap/fieldmap_solenoid.txt


# this should run quickly (no optical processes)
/MuSIC_Detector/gun/inputOffset 399
#/MuSIC_Detector/enableOpticalProcesses false
/MuSIC_Detector/enableOpticalProcesses true

/run/initialize
/run/beamOn 3
