#/usr/bin/bash

# generate macros that set a variety of thicknesses for the MuSIC5 sim
## Git commit hash: [`git branch` `git log --pretty=format:'%h' -n 1`]\n\
echo_bulk () 
{
    # gets the current branch & commit info
    gitcommit="$(git log --pretty=format:'%h' -n 1)" || gitcommit="not commited"
    gitbranch="$(git symbolic-ref HEAD 2>/dev/null)" || gitbranch="unnamed branch"
    gitbranch=${gitbranch##refs/heads/}
    bulk="\
#\n\
# This is an autogenerated file, do not modify it\n\
# File name: $3\n\
# Git branch: [$gitbranch]\n\
# Git commit hash: [$gitcommit] \n\
# Generated on: $(date)\n\
#\n\
# Optimising degrader\n\
#\t material:  $1\n\
#\t thickness: $2\n\
# \n\n\
/MuSIC_Detector/dipField ../../fieldmap/fieldmap_dipole.txt\n\
/MuSIC_Detector/solField ../../fieldmap/fieldmap_solenoid.txt\n\
\n\
/MuSIC_Detector/degraderMat $1\n\
/MuSIC_Detector/degraderZ $2 mm\n\
/run/initialize\n\
"
    echo -e $bulk
}

thicknesses=( 0.2 1 2 5 10 ) # degrader thicknesses in mm
materials=( Aluminium Polystyrene ) # & Polyethylene?

for mat in ${materials[@]};
do
    for thickness in ${thicknesses[@]}; 
    do
        filename="macros/run_${mat}_${thickness}mm.mac";
        outfile="../../output/run_${mat}_${thickness}mm.root"
        infile="../../g4blout/monitor6_By-0T_cor.root"
        exe="../../build/Release/music"
        echo_bulk $mat $thickness $filename > $filename
        echo "$exe $infile $outfile $filename"
    done;
done;