#/usr/bin/bash

# generate macros that set a variety of thicknesses for the MuSIC5 sim stoping target
## Git commit hash: [`git branch` `git log --pretty=format:'%h' -n 1`]\n\

# What's the name of this run?
runname="ST_optimisation" 
# what we want to generate
thicknesses=( 0.2 1 2 5 10 ) # target thicknesses in mm
materials=( Aluminium Polystyrene ) # & Polyethylene?


# locations etc
outfile_suf="root" # '.' is added at location, mainly for readability
macro_suf="mac"
log_suf="log"

root="../.."
infile="$root/g4blout/monitor6_By-0T_cor.root"
exedir="$root/build/Release"
exe="$exedir/music" # usage: ./music <in.root> <out.root> [run.mac]
outdir="$root/output"
logdir="$outdir/log"

runlog="$logdir/$runname.$log_suf" # master log


# gets the current branch & commit info
# repo info
gitcommit="$(git log --pretty=format:'%h' -n 1)" || gitcommit="not commited"
gitbranch="$(git symbolic-ref HEAD 2>/dev/null)" || gitbranch="unnamed branch"
gitbranch=${gitbranch##refs/heads/}

# standard header
header="#\n\
# This is an autogenerated header, do not modify it\n\
# Git commit: [$gitbranch $gitcommit]\n\
# Generated on: $(date)\n\
#"

# add the header to the runlog
echo -e $header"# File: $runlog \n" > $runlog

make_macro () 
{
    bulk="\
$header\
# File name: $3\n\
# Optimising stopping target\n\
#\t material:  $1\n\
#\t thickness: $2\n\
# \n\n\
/MuSIC_Detector/dipField ../../MuSIC5_detector/fieldmap/fieldmap_dipole.txt\n\
/MuSIC_Detector/solField ../../MuSIC5_detector/fieldmap/fieldmap_solenoid.txt\n\
\n\
/MuSIC_Detector/degraderMat Polystyrene\n\
/MuSIC_Detector/degraderZ 1 mm\n\
/MuSIC_Detector/targetMat $1\n\
/MuSIC_Detector/targetZ $2 mm\n\
/run/initialize\n\
"
    echo -e $bulk
}

# record exe status
echo "\`ls -l $exedir\` results in:" >> $runlog
ls -l $exedir >> $runlog 
echo -e "************************\n" >> $runlog

# generate the macros & run the program
for mat in ${materials[@]}; # loop over all entries in the array materials
do
    for thickness in ${thicknesses[@]}; 
    do
        prefix="${runname}_${mat}_${thickness}mm"
        outfile="$outdir/$prefix.$outfile_suf"
        macfile="$logdir/$prefix.$macro_suf" # save the macros with the logs
        logfile="$logdir/$prefix.$log_suf"
        make_macro $mat $thickness $macfile > $macfile
        echo "$mat $thickness run started" | tee -a $runlog 
        echo $macfile " generated" >> $runlog
        execmd="$exe $infile $outfile $macfile"
                # for an explanation of the below command see doit.sh
        cmd="( $execmd >> $logfile ) 2>&1 | tee -a $logfile $runlog"
        echo "Running command:" >> $runlog
        echo $cmd >> $runlog
        eval $cmd
        # this will also go to stdout
        echo "$mat $thickness run complete" | tee -a $runlog 
        echo -e "************************\n" >> $runlog
    done;
done;